import { css } from "@emotion/react"
import type { NextPage } from "next"
import Head from "next/head"

const container = css`
  width: 80rem;
  margin: 0 auto;
  padding: 10rem 0;
`

const h1Color = css`
  color: red;
`

const Home = (): JSX.Element => {
  return (
    <div css={container}>
      <Head>
        <title>Top Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 css={h1Color}>針と求人</h1>
      <p>test id:</p>
      <p>test name: </p>
    </div>
  )
}

export default Home
